# Generated by Django 3.2.6 on 2021-08-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favoris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('display_address', models.TextField()),
                ('display_phone', models.TextField()),
                ('rating', models.IntegerField(default=0)),
                ('image_url', models.TextField(default='')),
            ],
        ),
    ]
