# Generated by Django 3.2.6 on 2021-08-07 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210803_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoris',
            name='display_address',
        ),
        migrations.RemoveField(
            model_name='favoris',
            name='display_phone',
        ),
        migrations.RemoveField(
            model_name='favoris',
            name='rating',
        ),
    ]
