# Generated by Django 3.2.6 on 2021-08-08 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210807_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoris',
            name='business_id',
            field=models.CharField(default='DEFAULT VALUE', max_length=140),
        ),
    ]
